### ISSUE TITLE
missing two_wheel_robot_update.h and two_wheel_robot.h files

### ISSUE THREAD

**Issue by rusmanr** [yangliu28/swarm_robot_ros_sim#4]
Hi,
during catkin_make at position 77% two_wheel_robot_update.h and two_wheel_robot.h are not found.
could you help , where can i get these two files ?.
thanks

**Comment by YCH188** [comment]
@rusmanr Have you solve this problem? I encounter the same problem.

**Comment by yangliu28** [comment]
@rusmanr I'm closing this issue because it's been a while ago, and I assume you already resolved it. From what I can see, the ros message *two_wheel_robot.msg* has not been compiled, so there is no *two_wheel_robot.h* to be found. Try `catkin_make` on `swarm_robot_msgs` package only before processing the rest.
